### ISSUE TITLE
where can I get the ground truth?

### ISSUE THREAD

**Issue by h-k8888** [ntu-aris/ntu_viral_dataset#10]
thanks.

**Comment by brytsknguyen** [comment]
Hi, the groundtruth is under the topic `/leica/pose/relative' in the bag file. Please check out section 6 in our [paper](https://github.com/ntu-aris/ntu_viral_dataset/blob/gh-pages/docs/NTU_VIRAL_Dataset_Submission.pdf) to properly employ the ground truth.
