### ISSUE TITLE
Height euqiry

### ISSUE THREAD

**Issue by xuankugqz** [ntu-aris/ntu_viral_dataset#12]
Hi,

what is the height of the drone when recording the point cloud dataset?

Thanks a lot! :)

**Comment by snakehaihai** [comment]
Hi qizhi
When we fly the drone, there is no fixed height. The ground is about 50m AMSL. and we fly 5-30 meter above this height. During flight, the pointcloud is always been recorded.

**Comment by xuankugqz** [comment]
Thank you for your reply! This really make sense.

Wish you good luck!
________________________________
发件人: Yuan Shenghai ***@***.***>
发送时间: Saturday, September 17, 2022 8:44:06 PM
收件人: ntu-aris/ntu_viral_dataset ***@***.***>
抄送: GuoQizhi ***@***.***>; Author ***@***.***>
主题: Re: [ntu-aris/ntu_viral_dataset] Height euqiry (Issue #12)


Hi qizhi
When we fly the drone, there is no fixed height. The ground is about 50m AMSL. and we fly 5-30 meter above this height. During flight, the pointcloud is always been recorded.

―
