### ISSUE TITLE
outdoor wide scenario request

### ISSUE THREAD

**Issue by lyeemax** [ntu-aris/ntu_viral_dataset#13]
Dear author, thanks a lot for your contribution on this dataset. I wonder if you can provide some records of wide scenario like forest, farm or something.

**Comment by snakehaihai** [comment]
Hi, We are going to release a multi-campus dataset. Some place has forest-like environment. As for farms, we currently can't find such a place.

**Comment by lyeemax** [comment]
Really appreciate!!!

**Comment by brytsknguyen** [comment]
Hi @lyeemax
As snakehaihai mentioned, we are working on some datasets at wider scales, there will be significant vegetation in the environment. Please look out for our updates in March/April.

![image](https://user-images.githubusercontent.com/13504903/198013080-c3ef2dce-5bcf-4d02-a9a2-59fe2393d8f5.png)

![image](https://user-images.githubusercontent.com/13504903/198013218-37265b44-29e7-4ebb-9226-22129a4e0038.png)

**Comment by lyeemax** [comment]
Awesome! I'm working on fusing lidar and camera SLAM on degenerated scenario, what I need is extract your wide and rgb-colored dataset ,I wanna thank you again for feeding data in my project and this apple Easter egg:
![Screenshot from 2022-10-27 20-09-16](https://user-images.githubusercontent.com/48681352/198280618-65d1e81c-a5eb-463c-82a1-c1990e864d12.png)
Waiting for your new release!
