### ISSUE TITLE
building inspection datasets

### ISSUE THREAD

**Issue by lhthq** [ntu-aris/ntu_viral_dataset#15]
Hi, I am working on the Lidar-Inertia-Ranging fusion. And I did not find building inspection datasets in the VIRAL website. Could you please provide me the building inspection datasets with groundtruth? Thanks a lot!

**Comment by brytsknguyen** [comment]
Hi,

I am not sure if we can release the building inspection sequences as they were for some projects in collaboration with Singapore building and construction authority. @snakehaihai can confirm?

On the other hand, have you checked out the RTP and SPMS sequences? They are quite similar and may be more challenging than the building inspection sequences.

![image](https://github.com/ntu-aris/ntu_viral_dataset/assets/13504903/df884f6d-f0db-4d69-8bd1-d7b67c4a4d68)

**Comment by lhthq** [comment]
OK, thanks for replying. And the the upload sequences seem lacking of  rotation ground truth to evaluate the rotation error.

**Comment by snakehaihai** [comment]
@lhthq Currently, we don't have permission to release the HDB building inspection dataset. But if you want to, I can help to ask for such permission. Where are you based, and what is the purpose of using such a dataset?

**Comment by snakehaihai** [comment]
close the issue for inactive
