### ISSUE TITLE
Differences in ATE evaluation results for datasets

### ISSUE THREAD

**Issue by MatthewBlakeGE** [ntu-aris/ntu_viral_dataset#20]
First of all, thank you for the data set you provided. When I used your data set for benchmarking recently, I found that many papers had biases in the ATE evaluation of the data set. Your true value should be in the Leica coordinate system. Maybe many people’s algorithm results are output In the body (IMU) coordinate system, they did not perform coordinate system conversion and directly evaluated them. Therefore, the errors are relatively large.For example in the paper of FAST-LIVO: Fast and Tightly-coupled Sparse-Direct
LiDAR-Inertial-Visual Odometry.
![image](https://github.com/ntu-aris/ntu_viral_dataset/assets/100429035/8934916e-a524-45dc-9c38-7b5af4558900)
And in your Quick use
![image](https://github.com/ntu-aris/ntu_viral_dataset/assets/100429035/43309f34-eb34-43d0-9a4d-06b0cf4f0451) 
the results are:
![image](https://github.com/ntu-aris/ntu_viral_dataset/assets/100429035/fc4696e7-3c95-4ac6-b41b-d0a83dfc1c59)
In this evaluation of fast-lio, extrinsic_T should be [-0.05, 0.0, 0.055], because the extrinsic parameter in the paper is the conversion from lidar to imu. I used the wrong external parameters [0.05, 0.0, -0.055] to evaluate the eee_01 data set, and the result ATE was consistent with this, which was 0.13. After using the correct external parameters [-0.05, 0.0, 0.055], the result was 0.082.
 in your Quick use 
![image](https://github.com/ntu-aris/ntu_viral_dataset/assets/100429035/2b640c80-2589-4577-9981-e238f54e809a)
the results are:
![image](https://github.com/ntu-aris/ntu_viral_dataset/assets/100429035/92e8f96d-3475-4156-8fc0-a2e978f2a7ef)
The results in different papers and experiments are very different, and there should be errors in some papers.
 Can you confirm this for me? Thank you.

**Comment by brytsknguyen** [comment]
Hi,

I agree with your observations. It appears that FAST-LIVO overlooked the offset between the IMU and the Leica reference point, causing large bias error in the evaluation. When doing experiments, you should collect the 6DOF pose estimate and then convert it to the trajectory of the leica tracking point as explained in the [tutorial](https://ntu-aris.github.io/ntu_viral_dataset/evaluation_tutorial.html).

For the "lidar extrinsic parameter" (provided by our yaml file as T_B_L parameter), I think the most unambiguous definition is _the transform for coordinates in the lidar frame to the body frame_.  Another equivalent definition of extrinsic parameter is the _coordinate of the sensor with respect to the body frame_. That being said, we need to be aware that many people interpret the extrinsic parameters differently in the literature. Very often I need to input the inverse of the extrinsic parameters as I understand it when using others' works.

With that understanding, in case of FAST LIO, luckily the authors appear to have the same definition of extrinsic parameters like I do. So [-0.05, 0.0, 0.055] is the correct extrinsic. I figure this out by looking at their example https://github.com/hku-mars/FAST_LIO/blob/main/config/avia.yaml. In this case, you can see that they are using the inverse of the _offset of the IMU in the lidar point cloud coordinates_ in the [datasheet](https://terra-1-g.djicdn.com/65c028cd298f4669a7f0e40e50ba1131/demo/avia/Livox%20AVIA%20User%20Manual_EN.pdf) (see page 16).

For the SLICT paper, I confirm that the leica offsets and the extrinsics were both appropriately accounted for.

**Comment by MatthewBlakeGE** [comment]
Thank you very much for your reply, The SLICT paper, is the result of ATE represented by rmse ?.
