### ISSUE TITLE
Any launch or yaml files work for LVI-SAM?

### ISSUE THREAD

**Issue by h-k8888** [ntu-aris/ntu_viral_dataset#6]
I'm trying to do some experiments of LVI-SAM using NTU VIRAL dataset.
Any available launch or yaml files work for LVI-SAM?
Thanks.

**Comment by h-k8888** [comment]
I tryed https://github.com/brytsknguyen/LVI-SAM.
The Image Feature seems right, but the Image Depth seems wrong.
Is this just a display problem？
![Screenshot 2022-03-20 16:20:04](https://user-images.githubusercontent.com/68782862/159154182-b805570c-0f5e-4a23-941c-d1f4fc1e765c.png)

**Comment by brytsknguyen** [comment]
Hi,

Yes, I have been testing this method with NTU VIRAL dataset at the fork you reference.  The visual fusion seems to work normally when the parameters are configured probably. 

However the visual feature points appear to flip to the back of the camera. I think it's a visualization issue on the LVI's implementation side where the author assumed some fixed transform between the camera and the lidar.

![Screenshot from 2022-03-20 10-06-17](https://user-images.githubusercontent.com/13504903/159155525-5e603d33-971f-4bfe-8476-6ce0662fd62d.png)

If you can figure out how to make the visualization consistent I'd love to know too.

**Comment by h-k8888** [comment]
I tried. But as you said, there are some fixed transform in LVI-SAM, and the coordinate transformation is too complex. 
I haven't solved it yet.
 I'll let you know if it's solved.
Thanks.

**Comment by h-k8888** [comment]
![Screenshot 2022-04-03 00:23:17](https://user-images.githubusercontent.com/68782862/161392155-3f3f042d-6ec6-44be-ba56-4a7b99d5cd9c.png)
emmm.......
I think I solved this problem.
You need to modify a lot of code.

the extrinsic parameters from lidar to IMU, camera to IMU
in /src/visual_odometry/visual_estimator/utility/utility.h and /src/visual_odometry/visual_estimator/utility/visualization.cpp

and the lidar to camera frame
in /home/hk/ws_pl-lvi-sam/src/PL-LVI-SAM/src/visual_odometry/visual_feature/feature_tracker.h

**Comment by Stephen1e** [comment]
Hello, could you share the modified LVI-SAM code? It will be very helpful to me. Thank you in advance

**Comment by sp225** [comment]
> ![Screenshot 2022-04-03 00:23:17](https://user-images.githubusercontent.com/68782862/161392155-3f3f042d-6ec6-44be-ba56-4a7b99d5cd9c.png) emmm....... I think I solved this problem. You need to modify a lot of code.
> 
> the extrinsic parameters from lidar to IMU, camera to IMU in /src/visual_odometry/visual_estimator/utility/utility.h and /src/visual_odometry/visual_estimator/utility/visualization.cpp
> 
> and the lidar to camera frame in /home/hk/ws_pl-lvi-sam/src/PL-LVI-SAM/src/visual_odometry/visual_feature/feature_tracker.h

Hello, could you please share the modified code? It will be very helpful for me. Thank you very much.
