### ISSUE TITLE
Extrinsics between Lidar to IMU???

### ISSUE THREAD

**Issue by zuowei1998** [ntu-aris/ntu_viral_dataset#7]
**Describe the BUG**
Could u tell me the Extrinsics between Lidar to IMU???
Matrix<3, 3> R
Vector3d T
Thanks a lot!

**Comment by brytsknguyen** [comment]
Hi, which Lidar are you referring to?

When you download the dataset, the extrinsics are given in the yaml files:
![image](https://user-images.githubusercontent.com/13504903/163683911-b0662bff-a4fd-4ed3-9a68-ad9e8c10fa01.png)
![image](https://user-images.githubusercontent.com/13504903/163683980-6be70f72-64d7-4f39-a820-97c4e4572dc6.png)

For the horizontal lidar's extrinsics in the above, the lidar extrinsics are
Matrix<3, 3> R << 1, 0, 0, 0, 1, 0, 0, 0, 1;
Vector3d T << -0.05, 0, 0.055;

Note that the z axis of both the horizontal lidar and the IMU are pointing downward.
![image](https://user-images.githubusercontent.com/13504903/163684062-a1221c57-4b8c-44a7-9a60-81b0b8fc2308.png)


You can check out Section 4.4 in our paper for more information on the calibration.
https://github.com/ntu-aris/ntu_viral_dataset/blob/gh-pages/docs/NTU_VIRAL_Dataset_Submission.pdf

**Comment by zuowei1998** [comment]
Thank u for your answer! That's helpful for me!
One more thing is that when I download dataset, always download failed. Maybe "Internet wall" in china, do u have some link like baiduNetpan or AliNetpan? 
sincerely thanks!!!

**Comment by brytsknguyen** [comment]
Hi, does the download fail in the middle of the process or does it fail right when you start downloading?

Meanwhile, can you try downloading from NTU server below?
https://researchdata.ntu.edu.sg/dataset.xhtml?persistentId=doi:10.21979/N9/X39LEK

**Comment by snakehaihai** [comment]
> Thank u for your answer! That's helpful for me! One more thing is that when I download dataset, always download failed. Maybe "Internet wall" in china, do u have some link like baiduNetpan or AliNetpan? sincerely thanks!!!

We baiduPan and Alipan are extremely slow to work with on our campus. I can try to upload, but cant promise. Are you able to use otherways like google drive or dropbox?

**Comment by zuowei1998** [comment]
@brytsknguyen the download fail in the middle of the process. 
I have tried downloading from NTU server, but not work.

**Comment by zuowei1998** [comment]
@snakehaihai  google drive and dropbox are restricted in china. It's terrible.

**Comment by zuowei1998** [comment]
![error](https://user-images.githubusercontent.com/50592247/163799156-0336bc54-be3f-4c5e-abd4-c4caf0954374.png)

**Comment by snakehaihai** [comment]
Baidupan tooks 16 years to upload as the upload speed is in kbs.     
I`ll upload to some other online drive and see it if can work. WIll post the new link here in about 2 hours

**Comment by brytsknguyen** [comment]
Hi @zuowei1998, can you try downloading using wget in ubuntu:

`wget https://researchdata.ntu.edu.sg/api/access/datafile/68133`

The link for each file can be obtained by right-clicking and selecting "Copy link address" on the website:
![image](https://user-images.githubusercontent.com/13504903/163812143-b2de464f-5c69-4da2-8142-cfcda98db873.png)

**Comment by snakehaihai** [comment]
> ![error](https://user-images.githubusercontent.com/50592247/163799156-0336bc54-be3f-4c5e-abd4-c4caf0954374.png)

Hi This is the first link
Can you try if this service is workable in china?  

https://www.transfernow.net/dl/20220418j6WdhRxb

**Comment by snakehaihai** [comment]
@zuowei1998

This is the second link service

https://send.tresorit.com/a#vfsO82cl177z-BIPiQ-hJw

Can you try if this works ?

**Comment by zuowei1998** [comment]
@snakehaihai Both of them could be worked in china. But the second seem more better for free.hahaha~
I hope to get all of the dataset.Thanks~ 
@brytsknguyen I'm downloading from the command line. I don't know how it turns out. Good luck~

**Comment by snakehaihai** [comment]
> @snakehaihai Both of them could be worked in china. But the second seem more better for free.hahaha~ I hope to get all of the dataset.Thanks~ @brytsknguyen I'm downloading from the command line. I don't know how it turns out. Good luck~

ok i`ll send you the rest of the link tmr.

Rgs
Shenghai Yuan

**Comment by zuowei1998** [comment]
@brytsknguyen failed again. emmm maybe...
![fail](https://user-images.githubusercontent.com/50592247/163830819-77ed6eb6-d362-4e8b-8f7c-edb6f5f09da1.png)

**Comment by snakehaihai** [comment]
I`ll update the list here accordigly
EEE01
https://www.transfernow.net/dl/20220418j6WdhRxb   or   https://send.tresorit.com/a#vfsO82cl177z-BIPiQ-hJw

EEE02
https://www.transfernow.net/dl/20220419Yh1voEGW/SmTMAaJj or https://send.tresorit.com/a#qplsKEltu1g3AMvtRvJj6A

EEE03
https://www.transfernow.net/dl/20220419a4H2rmzH/B9JXMKC2  or https://send.tresorit.com/a#BI7uGqA-u2lFLEKhi5ZjfA

NYA01
https://www.transfernow.net/dl/20220419qQ81nzw7/iF4DYb5I or https://send.tresorit.com/a#zHjwerL0Spct1gXVl_F-Rw

NYA02
https://www.transfernow.net/dl/20220419HtmgHfss/K17jNNs2 or https://send.tresorit.com/a#GTpOM0S3e2GIfLFdnSeDPg

NYA03
https://www.transfernow.net/dl/20220419w9kzyf3Y/NJiCNqrX or https://send.tresorit.com/a#1BgEAYVzpjv74YT107-7vA

SBS01
https://www.transfernow.net/dl/202204197AlkiTNT/XFLTDw9v or https://send.tresorit.com/a#1jNmIMlR1EIToolAjk1FEA

SBS02
https://www.transfernow.net/dl/20220419oA1cWizp/btIjBwCP

SBS03
https://www.transfernow.net/dl/202204194vH2teS5/HMlyF8ic

**Comment by zuowei1998** [comment]
@snakehaihai Thank you very much. The download speed is very fast! Waiting for the remaining datasets to be updated.

**Comment by snakehaihai** [comment]
@zuowei1998 
I uploaded all bags and some additional groundtruth.
You may download them now. 

I`ll try to find a way to make the transfernow link permanent. But for now, those links will last for 1 week. So try to download them all asap


I`ll close this issue for now. If you have any other issue, you may open new tickets.

**Comment by snakehaihai** [comment]
@zuowei1998  
Can you help us to try if Microsoft cloud is allowed in china?
https://entuedu-my.sharepoint.com/:u:/g/personal/shyuan_staff_main_ntu_edu_sg/EbsL7sB6hbpLlqIoM2zkjHUBSQrgihrpq2_gN20sYveHJg?e=ALC8z8


https://entuedu-my.sharepoint.com/:u:/g/personal/shyuan_staff_main_ntu_edu_sg/Ea-8YoqbHjlPizIvpKyFCN0BfZQnIeL-m9e4LQVztfODvA?e=HymB52

**Comment by zuowei1998** [comment]
@snakehaihai China support for Microsoft cloud. But the speed is about 70% slower than above ways.about 800~900kb/s

**Comment by snakehaihai** [comment]
> @snakehaihai China support for Microsoft cloud. But the speed is about 70% slower than above ways.about 800~900kb/s

ok thx. Our school has free 1TB space for all student and staff with Microsoft cloud. We will be adding the microsfot link soon. Thanks for your help.
