### ISSUE TITLE
matlab script error!!!

### ISSUE THREAD

**Issue by zuowei1998** [ntu-aris/ntu_viral_dataset#8]
![2022-05-04 02-55-16 的屏幕截图](https://user-images.githubusercontent.com/50592247/166639938-68af1a80-02c1-48a1-b9e9-0a6480c82038.png)
do u know how to fix it??? thanks

**Comment by brytsknguyen** [comment]
Hi  @zuowei1998 I just replied to this on the aloam repo
https://github.com/brytsknguyen/A-LOAM/issues/1#issuecomment-1117173414

**Comment by brytsknguyen** [comment]
Copied from https://github.com/brytsknguyen/A-LOAM/issues/1#issuecomment-1117173414

You can comment out line 19 to 29, and line 32, and uncomment line 31 as follows:

```
% myCluster   = parcluster('local');
% 
% fprintf('Number of tests: %d. Number of Workers: %d\n\n',...
%          length(tests), myCluster.NumWorkers);
% 
% workers_needed = min(6, length(tests));
%      
% if myCluster.NumWorkers < workers_needed
%     delete(gcp);
%     parpool(workers_needed);
% end

for n=1:tests_count
% parfor n=1:tests_count
    
    [P_ate, rot_rmse] = check_viral_cal_err_parall(n, tests(n));

    EXP_NAME(n) = {tests(n).name(8:end)};
    P_ATE(n)    = {P_ate};
    R_ATE(n)    = {rot_rmse};
    
%     pause;
end
```
The commands from line 19 to 29 are to generate local worker pool to analyze the experiments in parallel to save time. The error may have something to do with your matlab subscription. Commenting them out make the analysis runs in sequence, which takes more time.
