### ISSUE TITLE
Any launch file can work on R2LIVE?

### ISSUE THREAD

**Issue by zuowei1998** [ntu-aris/ntu_viral_dataset#9]
**Describe the BUG**
I found your team's  work about R2LIVE for this dataset, but it seem not work. when I run "roslaunch r2live demo_ntuviral.launch"
, error occurs:cannot launch node of type [lvi_sam/lvi_sam_imuMod]: lvi_sam 
**To Reproduce**
roslaunch r2live demo_ntuviral.launch 
... logging to /home/zuowei/.ros/log/839dafb0-d029-11ec-85d9-b42e9954e44e/roslaunch-zuowei-B360M-GAMING-HD-4788.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://zuowei-B360M-GAMING-HD:38063/

SUMMARY
========

PARAMETERS
 * /acc_mul_G: 0
 * /fast_lio/T_Imu_Lidar: [1, 0, 0, -0.05, ...
 * /fast_lio/cube_side_length: 1000000000
 * /fast_lio/dense_map_enable: True
 * /fast_lio/filter_size_corner: 0.4
 * /fast_lio/filter_size_map: 0.4
 * /fast_lio/filter_size_surf: 0.4
 * /fast_lio/filter_size_surf_z: 0.4
 * /fast_lio/fov_degree: 360.0
 * /fast_lio/local_loop_win: [110, -116, 155, ...
 * /fast_lio/m_long_rang_pt_dis: 500
 * /fast_lio/map_file_path:  
 * /fast_lio/max_iteration: 4
 * /fast_lio/maximum_pt_kdtree_dis: 0.5
 * /fast_lio/maximum_res_dis: 0.3
 * /fast_lio/planar_check_dis: 0.1
 * /fast_lio/publish_feature_map: False
 * /feature_extraction/N_SCANS: 16
 * /feature_extraction/blind: 0.1
 * /feature_extraction/cos160: 160.0
 * /feature_extraction/disA: 0.01
 * /feature_extraction/disB: 0.1
 * /feature_extraction/edgea: 2
 * /feature_extraction/edgeb: 0.1
 * /feature_extraction/group_size: 8
 * /feature_extraction/inf_bound: 4
 * /feature_extraction/jump_down_limit: 8.0
 * /feature_extraction/jump_up_limit: 170.0
 * /feature_extraction/lidar_type: 3
 * /feature_extraction/limit_maxmid: 6.25
 * /feature_extraction/limit_maxmin: 3.24
 * /feature_extraction/limit_midmin: 6.25
 * /feature_extraction/p2l_ratio: 225
 * /feature_extraction/point_filter_num: 1
 * /feature_extraction/point_step: 3
 * /feature_extraction/smallp_intersect: 172.5
 * /feature_extraction/smallp_ratio: 1.2
 * /feature_extraction/using_raw_point: 1
 * /feature_tracker_r2live/config_file: /home/zuowei/catk...
 * /feature_tracker_r2live/image_topic: /right/image_raw
 * /feature_tracker_r2live/vins_folder: /home/zuowei/catk...
 * /if_dump_log: 0
 * /if_lidar_start_first: 1
 * /if_write_to_bag: 0
 * /imu_topic: /imu/imu_mod
 * /lidar_drag_cam_tim: 10
 * /lvi_sam_imuMod/imu_topic: /imu/imu
 * /lvi_sam_imuMod/tf_Bold_Bnew: [1, 0, 0, 0, 0, -...
 * /r2live/config_file: /home/zuowei/catk...
 * /r2live/vins_folder: /home/zuowei/catk...
 * /record_bag_name: /home/tmn/kitti_b...
 * /rosdistro: melodic
 * /rosversion: 1.14.12

NODES
  /
    feature_tracker_r2live (feature_tracker_r2live/feature_tracker_r2live)
    lio_feat_extract (r2live/lio_feat_extract)
    lvi_sam_imuMod (lvi_sam/lvi_sam_imuMod)
    r2live (r2live/r2live)
    rosbag_player_0 (rosbag/play)
    rvizvisualisation (rviz/rviz)

auto-starting new master
process[master]: started with pid [4812]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 839dafb0-d029-11ec-85d9-b42e9954e44e
process[rosout-1]: started with pid [4847]
started core service [/rosout]
process[feature_tracker_r2live-2]: started with pid [4854]
process[lio_feat_extract-3]: started with pid [4855]
OUST64
process[r2live-4]: started with pid [4864]
ERROR: cannot launch node of type [lvi_sam/lvi_sam_imuMod]: lvi_sam
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/zuowei/catkin_ws/NTU_R2LIVE1_WS/src
ROS path [2]=/home/zuowei/catkin_ws/ws_livox/src
ROS path [3]=/opt/ros/melodic/share
[ INFO] [1652163728.741882589]: init begins
[ INFO] [1652163728.748405981]: Loaded config_file: /home/zuowei/catkin_ws/NTU_R2LIVE1_WS/src/r2live/r2live/../config/ntuviral/filr_cam.yaml
result path /vins_result_no_loop.csv
 not exists, trying to create it 
Failed to create folder  
[ INFO] [1652163728.749170460]: ROW: 480.000000 COL: 752.000000 
[ WARN] [1652163728.749185909]:  fix extrinsic param 
[ INFO] [1652163728.749464111]: Extrinsic_R : 
-0.0191651 -0.0149622   0.999704
 -0.999744 -0.0117648 -0.0193419
 0.0120507  -0.999819 -0.0147329
[ INFO] [1652163728.749497413]: Extrinsic_T : 
0.00519443   -0.13478 -0.0146507
[ INFO] [1652163728.749519534]: Unsynchronized sensors, online estimate time offset, initial td: 0
[Ros_parameter]: /lidar_drag_cam_tim ==> 10
[Ros_parameter]: /acc_mul_G ==> 0
[Ros_parameter]: /if_lidar_start_first ==> 1
[Ros_parameter]: /if_write_to_bag ==> 0
[Ros_parameter]: /if_dump_log ==> 0
[Ros_parameter]: /record_bag_name ==> /home/tmn/kitti_bag/lic_record_bag/lic.bag
Multi thread started 
/home/zuowei/catkin_ws/NTU_R2LIVE1_WS/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 799
T_Imu_lidar
     1      0      0  -0.05
     0     -1      0      0
     0      0     -1 -0.055
     0      0      0      1
[Ros_parameter]: fast_lio/dense_map_enable ==> 1
[Ros_parameter]: fast_lio/lidar_time_delay ==> 0
[Ros_parameter]: fast_lio/max_iteration ==> 4
[Ros_parameter]: fast_lio/fov_degree ==> 360
[Ros_parameter]: fast_lio/filter_size_corner ==> 0.4
[Ros_parameter]: fast_lio/filter_size_surf ==> 0.4
[Ros_parameter]: fast_lio/filter_size_surf_z ==> 0.4
[Ros_parameter]: fast_lio/filter_size_map ==> 0.4
[Ros_parameter]: fast_lio/cube_side_length ==> 1e+09
[Ros_parameter]: fast_lio/maximum_pt_kdtree_dis ==> 0.5
[Ros_parameter]: fast_lio/maximum_res_dis ==> 0.3
[Ros_parameter]: fast_lio/planar_check_dis ==> 0.1
[Ros_parameter]: fast_lio/long_rang_pt_dis ==> 50
[Ros_parameter]: fast_lio/publish_feature_map ==> 0
/home/zuowei/catkin_ws/NTU_R2LIVE1_WS/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 833
/home/zuowei/catkin_ws/NTU_R2LIVE1_WS/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 846
/home/zuowei/catkin_ws/NTU_R2LIVE1_WS/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 848
[ WARN] [1652163728.789448189]: waiting for image and imu...
~~~~/home/zuowei/catkin_ws/NTU_R2LIVE1_WS/src/r2live/r2live/ doesn't exist
process[rvizvisualisation-6]: started with pid [4870]
process[rosbag_player_0-7]: started with pid [4879]
[FATAL] [1652163729.459207434]: Error opening file: /media/zuowei/T7/Dataset/NTU_VIRAL/nya_01.bag
[rosbag_player_0-7] process has died [pid 4879, exit code 1, cmd /opt/ros/melodic/lib/rosbag/play /media/zuowei/T7/Dataset/NTU_VIRAL/nya_01.bag -r 1 -s 0 __name:=rosbag_player_0 __log:=/home/zuowei/.ros/log/839dafb0-d029-11ec-85d9-b42e9954e44e/rosbag_player_0-7.log].
log file: /home/zuowei/.ros/log/839dafb0-d029-11ec-85d9-b42e9954e44e/rosbag_player_0-7*.log

sincerely thanks!

**Comment by snakehaihai** [comment]
Its R2live issue, not our dataset bug

R2Live uses Livox-like sparse 70-degree directional LIDAR for input, whereas our dataset uses Velodyne-like lightweight 360-degree FOV LIDAR. 

To use the 360 input, you may follow this comment here  https://github.com/hku-mars/r2live/issues/20  by update the fast lio inside the r2live.
